services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    build: .
    container_name: app_service
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: {}

networks:
  app-network:
    driver: bridge